import {
  MyRecoBox,
  NextImage,
  NextImgWrap,
  OthersImgBox,
  OthersName,
  OthersRatingBox,
  OthersReco,
  OthersRecoBox,
  OthersWrap,
  RecommendationsBox
} from "./style"

const MovieRecommendations = () => {
  return (
    <RecommendationsBox>
      <MyRecoBox>
        <div></div>
        <span>我來評論</span>
        <NextImage
          src="/images/star-circle.png"
          alt=""
          width={44}
          height={44}
        />
        <NextImage
          src="/images/star-circle.png"
          alt=""
          width={44}
          height={44}
        />
        <NextImage
          src="/images/star-circle.png"
          alt=""
          width={44}
          height={44}
        />
        <NextImage
          src="/images/star-circle.png"
          alt=""
          width={44}
          height={44}
        />
        <NextImage
          src="/images/star-circle.png"
          alt=""
          width={44}
          height={44}
        />
      </MyRecoBox>
      <OthersRecoBox>
        <OthersWrap>
          <OthersImgBox>
            <NextImage
              src="/images/title-profile-pc.png"
              alt=""
              width={46}
              height={46}
            />
          </OthersImgBox>
          <OthersReco>
            <OthersName>陳大明</OthersName>
            <OthersRatingBox>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
            </OthersRatingBox>
            <p>老實說要不是演員感覺很努力在演，連兩顆星都懶得給.....</p>
          </OthersReco>
        </OthersWrap>
        <OthersWrap>
          <OthersImgBox>
            <NextImage
              src="/images/title-profile-pc.png"
              alt=""
              width={46}
              height={46}
            />
          </OthersImgBox>
          <OthersReco>
            <OthersName>陳大明</OthersName>
            <OthersRatingBox>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
            </OthersRatingBox>
            <p>老實說要不是演員感覺很努力在演，連兩顆星都懶得給.....</p>
          </OthersReco>
        </OthersWrap>
        <OthersWrap>
          <OthersImgBox>
            <NextImage
              src="/images/title-profile-pc.png"
              alt=""
              width={46}
              height={46}
            />
          </OthersImgBox>
          <OthersReco>
            <OthersName>陳大明</OthersName>
            <OthersRatingBox>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
            </OthersRatingBox>
            <p>老實說要不是演員感覺很努力在演，連兩顆星都懶得給.....</p>
          </OthersReco>
        </OthersWrap>
        <OthersWrap>
          <OthersImgBox>
            <NextImage
              src="/images/title-profile-pc.png"
              alt=""
              width={46}
              height={46}
            />
          </OthersImgBox>
          <OthersReco>
            <OthersName>陳大明</OthersName>
            <OthersRatingBox>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
            </OthersRatingBox>
            <p>老實說要不是演員感覺很努力在演，連兩顆星都懶得給.....</p>
          </OthersReco>
        </OthersWrap>
        <OthersWrap>
          <OthersImgBox>
            <NextImage
              src="/images/title-profile-pc.png"
              alt=""
              width={46}
              height={46}
            />
          </OthersImgBox>
          <OthersReco>
            <OthersName>陳大明</OthersName>
            <OthersRatingBox>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
              <NextImgWrap>
                <NextImage
                  src="/images/white-star.png"
                  alt=""
                  width={17}
                  height={17}
                />
              </NextImgWrap>
            </OthersRatingBox>
            <p>老實說要不是演員感覺很努力在演，連兩顆星都懶得給.....</p>
          </OthersReco>
        </OthersWrap>
      </OthersRecoBox>
    </RecommendationsBox>
  )
}

export default MovieRecommendations
