import React from "react"
import Head from "next/head"

const HomeMeta = () => {
  return (
    <Head>
      <title>wtw-movie-next</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/Logo.png" />
    </Head>
  )
}

export default HomeMeta
